name: Publish mkdocs via GitHub Pages
on:
  push:
    branches:
      - mkdocs

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Install sys deps
        run: |
          sudo apt update && sudo apt install -y bibtool
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: omnibenchmark.org
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
